modular setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,6 +2,26 @@
 
 set -e
 
+echo "Choose your adventure:
+============================
+1. Shell/CLI stuff only
+2. Above plus basic GUI 
+3. Above plus extras like steam, messengers (bloat)
+"
+read -p "Enter number[1-3]: " input
+
+if ! [ "$input" -eq "$input" ] 2> /dev/null; then
+
+    echo "Error: Not a number"
+    exit 1
+
+elif [ $input -lt 1 ] || [ $input -gt 3 ]; then
+
+    echo "Error: Input out of range"
+    exit 1
+
+fi
+
 # Trigger sudo prompt before less can block password input
 sudo echo ''
 
@@ -47,7 +67,7 @@ if [[ $OS == *Arch* ]]; then
             git clone https://github.com/adoyle0/Doors.git .doors
         fi
 
-        $HOME/.doors/scripts/install_arch
+        $HOME/projects/Doors/scripts/install_arch $input
 
 # These are broken for now
 # elif [[ $OS == *buntu* ]]; then
@@ -73,7 +93,7 @@ git submodule init && git submodule update
 
 # Copy and link files
 cd $HOME/.doors &&
-$HOME/.doors/scripts/copy_and_link
+$HOME/.doors/scripts/copy_and_link $input
 
 # Copy default wallpaper
 if ! test -d $HOME/Pictures; then
